### ISSUE TITLE
"Tensor %s is not an element of this graph." Error

### ISSUE THREAD

**Issue by wanshun123** [jrosebr1/simple-keras-rest-api#5]
I've cloned the repository and tried to run it with no changes. I've ran `python run_keras_server.py` to start the server (no issues) and then run `python simple_request.py`, which results in an error. I get the following.

From the `run_keras_server.py` command window:

```
[2018-08-16 14:46:10,048] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_keras_server.py", line 61, in predict
    preds = model.predict(image)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1162, in predict
    self._make_predict_function()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 543, in _make_predict_function
    **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2695, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2516, in __init__
    with tf.control_dependencies(self.outputs):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 5060, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 4664, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3613, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3692, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("fc1000/Softmax:0", shape=(?, 1000), dtype=float32) is not an element of this graph.
127.0.0.1 - - [16/Aug/2018 14:46:10] "[1m[35mPOST /predict HTTP/1.1[0m" 500 -
```

From the `simple_request.py` command window:

```
Traceback (most recent call last):
  File "simple_request.py", line 17, in <module>
    r = requests.post(KERAS_REST_API_URL, files=payload).json()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wanshun123** [comment]
Per https://github.com/keras-team/keras/issues/2397 I replaced `app.run()` in `run_keras_server.py` with `app.run(debug = False, threaded = False)`

**Comment by Realvincentyuan** [comment]
> Per [keras-team/keras#2397](https://github.com/keras-team/keras/issues/2397) I replaced `app.run()` in `run_keras_server.py` with `app.run(debug = False, threaded = False)`

Did it work? It does not work for me in fact. I am trying to replicate the [post ](https://blog.keras.io/building-a-simple-keras-deep-learning-rest-api.html)and met the same error
